import type { CatalogProduct } from '@/lib/products-data';

const ISLAMIC_CATEGORY_NAME = 'ইসলামিক';

const DELIVERY =
  'ঢাকার ভিতরে ২-৩ কর্মদিবস, ঢাকার বাইরে ৩-৭ কর্মদিবস। ক্যাশ অন ডেলিভারি।';
const RETURNS =
  '৭ দিনের মধ্যে অব্যবহৃত পণ্য রিটার্ন করা যাবে। পণ্য অবশ্যই মূল অবস্থায় ও মোড়কসহ থাকতে হবে।';

function islamicProduct(
  input: Omit<
    CatalogProduct,
    'categorySlug' | 'categoryName' | 'href' | 'productType' | 'published' | 'inStock'
  > & { categorySlug?: never }
): CatalogProduct {
  return {
    ...input,
    categorySlug: 'islamic',
    categoryName: ISLAMIC_CATEGORY_NAME,
    href: `/products/${input.slug}`,
    productType: 'simple',
    published: true,
    inStock: true,
  };
}

/** Imported from smartchinahub Islamic collection (excludes Murda Moshari). */
export const ISLAMIC_CATALOG_PRODUCTS: CatalogProduct[] = [
  islamicProduct({
    id: 'premium-jaynamaz-j2',
    slug: 'premium-jaynamaz-j2',
    title: 'প্রিমিয়াম আমদানি জায়নামাজ — জেডেন মোটিফ',
    price: 990,
    bgClass: 'bg-[#1e3a2f]',
    colors: [],
    sizes: [],
    rating: 4.8,
    reviewCount: 42,
    aspectRatio: '1/1',
    description:
      'নামাজের শান্তি ও মনোযোগের জন্য নরম, ঘন ও টেকসই জায়নামাজ। চীন থেকে সরাসরি আমদানি — প্রতিটি পিস আলাদা জেডেন ইসলামিক মোটিফে সাজানো।\n\nমূল বৈশিষ্ট্য:\n• উচ্চ ঘনত্বের ফ্লিস টপ — ঠান্ডা মেঝেতেও আরামদায়ক\n• নন-স্লিপ পিছনের পৃষ্ঠ — সুজুদে স্থির থাকে\n• হালকা ও ভাঁজে নেওয়া সহজ — ভ্রমণে বহন করতে সুবিধা\n• সহজ পরিচ্ছন্নতা — হালকা ঝাড়ু বা হাতে ধোয়া\n\nস্পেসিফিকেশন:\nউচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | ওজন: হালকা (প্রায় ৬৫০–৭৫০ গ্রাম) | উপাদান: সিন্থেটিক ফ্লিস + নন-স্লিপ ব্যাকিং',
    materialCare:
      'নিয়মিত হালকা ঝাড়ু দিন। ভেজা কাপড়ে মুছে শুকিয়ে নিন; ব্লিচ বা কড়া রাসায়নিক ব্যবহার করবেন না।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#1e3a2f]', url: '/products/islamic/jaynamaz-j2.jpg' }],
    popularScore: 82,
    createdAt: Date.now() - 86400000 * 2,
    tags: ['জায়নামাজ', 'ইসলামিক', 'নামাজ', 'প্রিমিয়াম'],
    sku: 'ALM-ISL-002',
    fabric: 'ফ্লিস টপ, নন-স্লিপ ব্যাকিং',
  }),
  islamicProduct({
    id: 'premium-jaynamaz-j4',
    slug: 'premium-jaynamaz-j4',
    title: 'প্রিমিয়াম আমদানি জায়নামাজ — গোল্ডেন আরাবেস্ক',
    price: 990,
    bgClass: 'bg-[#3d2c1e]',
    colors: [],
    sizes: [],
    rating: 4.7,
    reviewCount: 38,
    aspectRatio: '1/1',
    description:
      'দৈনিক নামাজ ও তাহাজ্জুদের জন্য আরামদায়ক, স্টাইলিশ জায়নামাজ। সোনালি-ক্রিম টোনের আরাবেস্ক প্যাটার্ন পরিবারের যেকোনো ঘরে মানানসই।\n\nমূল বৈশিষ্ট্য:\n• মোটা কুশনিং — দীর্ঘ সিজদায় কম্প্রেস হয় না\n• অ্যান্টি-স্লিপ বেস — টাইল ও মার্বেল মেঝেতে নিরাপদ\n• ফেড প্রুফ প্রিন্ট — বারবার ধোয়ার পরেও রঙ টিকে থাকে\n• উপহারের জন্য উপযুক্ত প্যাকেজিং\n\nস্পেসিফিকেশন:\nউচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | প্যাটার্ন: গোল্ডেন আরাবেস্ক | কোড রেফ: J4',
    materialCare: 'শুকনো ঝাড়ু দিয়ে রাখুন। প্রয়োজনে হালকা সাবান পানি; সরাসরি রোদে দীর্ঘ সময় শুকাবেন না।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#3d2c1e]', url: '/products/islamic/jaynamaz-j4.jpg' }],
    popularScore: 80,
    createdAt: Date.now() - 86400000 * 3,
    tags: ['জায়নামাজ', 'ইসলামিক', 'উপহার'],
    sku: 'ALM-ISL-003',
    fabric: 'প্রিমিয়াম ফ্লিস, অ্যান্টি-স্লিপ বেস',
  }),
  islamicProduct({
    id: 'premium-jaynamaz-j5',
    slug: 'premium-jaynamaz-j5',
    title: 'প্রিমিয়াম আমদানি জায়নামাজ — ক্লাসিক মসজিদ প্রিন্ট',
    price: 990,
    bgClass: 'bg-[#2a3d4f]',
    colors: [],
    sizes: [],
    rating: 4.8,
    reviewCount: 51,
    aspectRatio: '1/1',
    description:
      'মসজিদ-ইনস্পায়ার্ড প্রিন্টসহ আমদানি জায়নামাজ যা নামাজের মুহূর্তকে আরও শান্তিময় করে তোলে। নরম স্পর্শ, দ্রুত শুকানো উপাদান।\n\nমূল বৈশিষ্ট্য:\n• ক্লাসিক মিনারেট ও গম্বুজ মোটিফ\n• দীর্ঘস্থায়ী সেলাই — কোণা ছিঁড়ে যায় না সহজে\n• অফিস, মসজিদ বা ভ্রমণ — সব জায়গায় ব্যবহারযোগ্য\n• বাচ্চাদের তাহরিম শেখানোর জন্যও উপযুক্ত সাইজ\n\nস্পেসিফিকেশন:\nউচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | প্রিন্ট: মসজিদ মোটিফ | কোড রেফ: J5',
    materialCare: 'ধুলা ঝাড়ার পর ভাঁজ করে রাখুন। ভেজা থাকলে সম্পূর্ণ শুকিয়ে ব্যবহার করুন।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#2a3d4f]', url: '/products/islamic/jaynamaz-j5.jpg' }],
    popularScore: 84,
    createdAt: Date.now() - 86400000 * 4,
    tags: ['জায়নামাজ', 'ইসলামিক', 'মসজিদ প্রিন্ট'],
    sku: 'ALM-ISL-004',
    fabric: 'ফ্লিস টপ, নন-স্লিপ বেস',
  }),
  islamicProduct({
    id: 'islamic-seven-books-bundle',
    slug: 'islamic-seven-books-bundle',
    title: 'ইসলামিক জ্ঞানবান্ধব সাত-বই কম্বো সেট',
    price: 980,
    compareAtPrice: 1755,
    bgClass: 'bg-[#4a3728]',
    colors: [],
    sizes: [],
    rating: 4.9,
    reviewCount: 67,
    aspectRatio: '1/1',
    description:
      'নতুন মুসলিম, তরুণ ও পরিবারের জন্য সাতটি গুরুত্বপূর্ণ ইসলামিক বই এক প্যাকেজে — পড়া, শেখা ও উপহার দেওয়ার জন্য আদর্শ।\n\nমূল বৈশিষ্ট্য:\n• সাতটি বেস্টসেলার বিষয় — আকিদা, ইবাদত, আখলাক ও দৈনন্দিন ফিকহ\n• বাংলা/সহজ ভাষায় বোঝার মতো মুদ্রণ\n• একবারে কম দামে সম্পূর্ণ লাইব্রেরি স্টার্টার\n• ঈদ, কামাইয়ের মাহফিল বা নতুন ঘরে উপহার হিসেবে জনপ্রিয়\n\nস্পেসিফিকেশন:\nপ্যাকেজ: ৭ বই কম্বো | ভাষা: বাংলা/সহ-বাংলা (প্রকাশনা অনুযায়ী) | বাইন্ডিং: পেপারব্যাক কম্বো | কোড রেফ: 7-B',
    materialCare: 'শুকনো, সূর্যালোক এড়িয়ে রাখুন। পানি লাগলে তৎক্ষণাত শুকিয়ে নিন।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#4a3728]', url: '/products/islamic/islamic-7-books.jpg' }],
    popularScore: 88,
    createdAt: Date.now() - 86400000 * 1,
    tags: ['ইসলামিক বই', 'কম্বো', 'ইসলামিক শিক্ষা', 'উপহার'],
    sku: 'ALM-ISL-005',
    fabric: 'পেপারব্যাক বই সেট',
  }),
  islamicProduct({
    id: 'solid-jaynamaz-black',
    slug: 'solid-jaynamaz-black',
    title: 'সলিড কালো প্রিমিয়াম জায়নামাজ',
    price: 1290,
    bgClass: 'bg-[#1a1a1a]',
    colors: [{ id: 'black', name: 'কালো', hex: '#1a1a1a' }],
    sizes: [],
    rating: 4.8,
    reviewCount: 29,
    aspectRatio: '1/1',
    description:
      'গাঢ় কালো একরঙের জায়নামাজ — মিনিমালিস্ট প্রিয়দের জন্য। মসজিদ, অফিস বা ভ্রমণে ব্যবহারের জন্য পরিষ্কার লুক।\n\nমূল বৈশিষ্ট্য:\n• একরঙ সলিড কালো — কোনো ব্যসি প্রিন্ট নয়\n• অতিরিক্ত মোটা ফ্লিস — ১২৯০ টাকা গ্রেডের কুশন\n• নন-স্লিপ ব্যাকিং — মার্বেল মেঝেতে স্লিপ হয় না\n• সহজ ভাঁজ — ব্যাগে কম জায়গা\n\nস্পেসিফিকেশন:\nরঙ: কালো | উচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | কোড: j101',
    materialCare: 'নিয়মিত ঝাড়ুন; হালকা সাবান পানিতে হাতে ধোয়া যায়।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#1a1a1a]', url: '/products/islamic/jaynamaz-black.jpg' }],
    popularScore: 78,
    createdAt: Date.now() - 86400000 * 5,
    tags: ['জায়নামাজ', 'কালো', 'সলিড'],
    sku: 'ALM-ISL-006',
    fabric: 'হাই-ডেনসিটি ফ্লিস',
  }),
  islamicProduct({
    id: 'solid-jaynamaz-ash',
    slug: 'solid-jaynamaz-ash',
    title: 'সলিড অ্যাশ গ্রে জায়নামাজ',
    price: 1290,
    bgClass: 'bg-[#6b6b6b]',
    colors: [{ id: 'ash', name: 'অ্যাশ', hex: '#8a8a85' }],
    sizes: [],
    rating: 4.7,
    reviewCount: 22,
    aspectRatio: '1/1',
    description:
      'নরম অ্যাশ গ্রে টোনের জায়নামাজ যা আধুনিক ইন্টেরিয়রের সাথে মিশে যায়। দৈনিক পাঁচ ওয়াক্ত নামাজের জন্য আরামদায়ক।\n\nমূল বৈশিষ্ট্য:\n• মিনিমাল অ্যাশ রঙ — লিভিং রুমে রেখে দেওয়া যায়\n• প্রিমিয়াম থিকনেস ফ্লিস\n• অ্যান্টি-স্লিপ পিছন\n• দ্রুত শুকানো উপাদান\n\nস্পেসিফিকেশন:\nরঙ: অ্যাশ গ্রে | উচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | কোড: j102',
    materialCare: 'শুকনো স্থানে সংরক্ষণ করুন; সাপ্তাহিক হালকা পরিষ্কার।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#6b6b6b]', url: '/products/islamic/jaynamaz-ash.jpg' }],
    popularScore: 76,
    createdAt: Date.now() - 86400000 * 6,
    tags: ['জায়নামাজ', 'গ্রে', 'মিনিমাল'],
    sku: 'ALM-ISL-007',
    fabric: 'হাই-ডেনসিটি ফ্লিস',
  }),
  islamicProduct({
    id: 'solid-jaynamaz-green',
    slug: 'solid-jaynamaz-green',
    title: 'সলিড সবুজ প্রিমিয়াম জায়নামাজ',
    price: 1290,
    bgClass: 'bg-[#2d4a3e]',
    colors: [{ id: 'green', name: 'সবুজ', hex: '#2d4a3e' }],
    sizes: [],
    rating: 4.8,
    reviewCount: 31,
    aspectRatio: '1/1',
    description:
      'ইসলামিক সবুজ টোনের সলিড জায়নামাজ — চোখে শান্তি দেয়, নামাজে মনোযোগ বাড়ায়। ঘন ফ্লিস ও নরম স্পর্শ।\n\nমূল বৈশিষ্ট্য:\n• গাঢ় সবুজ একরঙ\n• অতিরিক্ত কুশন স্তর\n• নন-স্লিপ বেস\n• উপহার বা ব্যক্তিগত ব্যবহার — উভয়ের জন্য\n\nস্পেসিফিকেশন:\nরঙ: সবুজ | উচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | কোড: j103',
    materialCare: 'হালকা ঝাড়ু; ভেজা থাকলে সম্পূর্ণ শুকিয়ে নিন।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#2d4a3e]', url: '/products/islamic/jaynamaz-green.jpg' }],
    popularScore: 79,
    createdAt: Date.now() - 86400000 * 7,
    tags: ['জায়নামাজ', 'সবুজ', 'ইসলামিক'],
    sku: 'ALM-ISL-008',
    fabric: 'হাই-ডেনসিটি ফ্লিস',
  }),
  islamicProduct({
    id: 'solid-jaynamaz-cream',
    slug: 'solid-jaynamaz-cream',
    title: 'সলিড ক্রিম টোন জায়নামাজ',
    price: 1290,
    bgClass: 'bg-[#e8dfd0]',
    colors: [{ id: 'cream', name: 'ক্রিম', hex: '#e8dfd0' }],
    sizes: [],
    rating: 4.7,
    reviewCount: 26,
    aspectRatio: '1/1',
    description:
      'হালকা ক্রিম রঙের জায়নামাজ — উজ্জ্বল ঘর, হালকা ফ্লোরিং বা শীতকালীন ব্যবহারের জন্য আরামদায়ক।\n\nমূল বৈশিষ্ট্য:\n• নরম ক্রিম শেড\n• দাগ কম দেখা যায় হালকা রঙে\n• মোটা ফ্লিস লেয়ার\n• ভ্রমণ ও অতিথি নামাজের জন্য উপযুক্ত\n\nস্পেসিফিকেশন:\nরঙ: ক্রিম | উচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | কোড: j104',
    materialCare: 'নিয়মিত ঝাড়ুন; গাঢ় দাগ এড়িয়ে হালকা সাবান ব্যবহার করুন।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#e8dfd0]', url: '/products/islamic/jaynamaz-cream.jpg' }],
    popularScore: 77,
    createdAt: Date.now() - 86400000 * 8,
    tags: ['জায়নামাজ', 'ক্রিম'],
    sku: 'ALM-ISL-009',
    fabric: 'হাই-ডেনসিটি ফ্লিস',
  }),
  islamicProduct({
    id: 'solid-jaynamaz-white',
    slug: 'solid-jaynamaz-white',
    title: 'সলিড সাদা প্রিমিয়াম জায়নামাজ',
    price: 1290,
    bgClass: 'bg-[#f5f5f0]',
    colors: [{ id: 'white', name: 'সাদা', hex: '#f5f5f0' }],
    sizes: [],
    rating: 4.8,
    reviewCount: 34,
    aspectRatio: '1/1',
    description:
      'পরিষ্কার সাদা সলিড জায়নামাজ — জুমুআ, ঈদগাহ বা বিশেষ দিনের নামাজের জন্য পছন্দের রঙ। প্রিমিয়াম ঘনত্ব ও নরম স্পর্শ।\n\nমূল বৈশিষ্ট্য:\n• উজ্জ্বল সাদা একরঙ\n• অ্যান্টি-স্লিপ বেস\n• সহজ পরিষ্কার — হালকা সাবানেই ধোয়া যায়\n• উপহার প্যাকেজিং উপলব্ধ\n\nস্পেসিফিকেশন:\nরঙ: সাদা | উচ্চতা: প্রায় ১১০ সে.মি. | প্রস্থ: প্রায় ৭০ সে.মি. | কোড: j105',
    materialCare: 'পৃথক ধোয়া ভালো; রোদে শুকানোর সময় রঙ হলুদ হতে পারে — ছায়ায় শুকান।',
    deliveryInfo: DELIVERY,
    returnPolicy: RETURNS,
    images: [{ id: '1', bgClass: 'bg-[#f5f5f0]', url: '/products/islamic/jaynamaz-white.jpg' }],
    popularScore: 81,
    createdAt: Date.now() - 86400000 * 9,
    tags: ['জায়নামাজ', 'সাদা', 'ঈদ'],
    sku: 'ALM-ISL-010',
    fabric: 'হাই-ডেনসিটি ফ্লিস',
  }),
];
